### ISSUE TITLE
make video preview fullscreen 

### ISSUE THREAD

**Issue by kernelheart** [saki4510t/AudioVideoRecordingSample#1]
Hi,
 thanks for your effort. 
Could you please help me how to make video preview fullscreen in portrait mode 
Thanks.

**Comment by saki4510t** [comment]
Hello,

Could you try this way?
1) comment out line291-309 in CameraGLView.java (in #updateViewport method)
comment out from line "GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT);"
to line "GLES20.glViewport(w, h, width, height);"

This way render camera image onto entire surface of CameraGLView.

If you need to crop center of camera image and fill it to entire surface, you need calculate viewport dimensions here.

with best regards,
saki

**Comment by kernelheart** [comment]
Hi, 
Thank you very much. It works !!!
