### ISSUE TITLE
Crop frame before encoding it

### ISSUE THREAD

**Issue by VictorOjeda** [saki4510t/AudioVideoRecordingSample#5]
Hi Saki,

First, thank you for your share. I would like to know if there is a way to crop/manipulate each frame before encoding it.

**Comment by saki4510t** [comment]
Hi,
I add some code to apply mvp matrix to recording images.
You can change mvp matrix as you want(as you can see some sample matrix in `updateViewport` method in `CameraGLView.java`).
saki
